# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the application
RUN npm run build

# Expose port if needed, though MCP servers may not need it

# Command to run the app
CMD ["node", "build/index.js"]
